### ISSUE TITLE
output file extension should be `.html`?

### ISSUE THREAD

**Issue by indigofeather** [MadcapJake/fly-marked#1]
Hello

In the example:

``` js
export function* md () {
  yield this
    .source("src/**/*.md")
    .marked()
    .concat("test.html")
    .target("dist")
}
```

If we don't want `concat()`, it will output all files in separated `.md`.
Perhaps this line (https://github.com/MadcapJake/fly-marked/blob/master/index.js#L8) should be `.html`?

**Comment by MadcapJake** [comment]
Well that line actually sets what files are passed to the filter (only `.md` files).  Let me see if I can find a way to specify an output file extension.

**Comment by indigofeather** [comment]
I'm not sure if I misunderstand the usage of `filter`. :smile:
 In `fly-coffee`, it uses `.js`: https://github.com/bucaran/fly-coffee/blob/master/index.js#L5

And I try to use `.html` in `fly-marked`, it works fine.

**Comment by MadcapJake** [comment]
Oh! You're right, I read that wrong! Thanks @indigofeather !

**Comment by MadcapJake** [comment]
That should do it!  :+1:

**Comment by indigofeather** [comment]
Thank you! :+1:
